services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      OWNER_ID: $OWNER_ID
      BIN_CHANNEL: $BIN_CHANNEL
      DATABASE_URL: $DATABASE_URL
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
